Improve help output, add debug option

diff --git a/manpdf b/manpdf
--- a/manpdf
+++ b/manpdf
@@ -3,10 +3,11 @@
 # Created by argbash-init v2.10.0
 # ARG_OPTIONAL_SINGLE([output],[o],[The output file])
 # ARG_OPTIONAL_BOOLEAN([open-pdf],[],[Open the PDF file after creating it],[on])
+# ARG_OPTIONAL_BOOLEAN([debug],[d],[Print debug information too],[off])
 # ARG_POSITIONAL_SINGLE([name-or-file])
 # ARG_POSITIONAL_SINGLE([section],[],[""])
 # ARG_DEFAULTS_POS([])
-# ARG_HELP([<Open a man page as a PDF file>])
+# ARG_HELP([ManPDF - Open a man page as a PDF file.],[ManPDF should work everywhere that has: \n - A 'man' implementation,\n - 'groff', and\n - 'open' or 'xdg-open' associated with an application that can open PDFs.],[h],[help],[Prints this help])
 # ARG_VERSION([echo $(basename $0) 420.69])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
@@ -26,7 +27,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='ohv'
+	local first_option all_short_options='odhv'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -38,16 +39,22 @@ _arg_section=""
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_output=
 _arg_open_pdf="on"
+_arg_debug="off"
 
 
 print_help()
 {
-	printf '%s\n' "<Open a man page as a PDF file>"
-	printf 'Usage: %s [-o|--output <arg>] [--(no-)open-pdf] [-h|--help] [-v|--version] <name-or-file> [<section>]\n' "$(basename $0)"
+	printf '%s\n' "ManPDF - Open a man page as a PDF file."
+	printf 'Usage: %s [-o|--output <arg>] [--(no-)open-pdf] [-d|--(no-)debug] [-h|--help] [-v|--version] <name-or-file> [<section>]\n' "$0"
 	printf '\t%s\n' "-o, --output: The output file (no default)"
 	printf '\t%s\n' "--open-pdf, --no-open-pdf: Open the PDF file after creating it (on by default)"
-	printf '\t%s\n' "-h, --help: Prints help"
+	printf '\t%s\n' "-d, --debug, --no-debug: Print debug information too (off by default)"
+	printf '\t%s\n' "-h, --help: Prints this help"
 	printf '\t%s\n' "-v, --version: Prints version"
+	printf '\n%s\n' "ManPDF should work everywhere that has:
+ - A 'man' implementation,
+ - 'groff', and
+ - 'open' or 'xdg-open' associated with an application that can open PDFs."
 }
 
 
@@ -72,6 +79,18 @@ parse_commandline()
 			--no-open-pdf|--open-pdf)
 				_arg_open_pdf="on"
 				test "${1:0:5}" = "--no-" && _arg_open_pdf="off"
+				;;
+			-d|--no-debug|--debug)
+				_arg_debug="on"
+				test "${1:0:5}" = "--no-" && _arg_debug="off"
+				;;
+			-d*)
+				_arg_debug="on"
+				_next="${_key##-d}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
 				;;
 			-h|--help)
 				print_help
@@ -162,7 +181,16 @@ fi
 
 echo "Generating PDF for '$NAME'"
 
-groff -Tpdf -mandoc -c $FILE > $OUTPUT
+# store the command to run
+COMMAND="groff -Tpdf -mandoc -c $FILE > $OUTPUT"
+
+# if debug is on, print the command
+if [[ "$_arg_debug" == "on" ]]; then
+  echo "Running command: $COMMAND"
+fi
+
+# run the command
+eval $COMMAND
 
 # open the file if we are told to
 if [[ "$_arg_open_pdf" == "on" ]]; then
@@ -171,6 +199,11 @@ if [[ "$_arg_open_pdf" == "on" ]]; then
   OPEN="open"
   if ! command -v $OPEN &> /dev/null; then
     OPEN="xdg-open"
+  fi
+
+  # if debug is on, print the open program
+  if [[ "$_arg_debug" == "on" ]]; then
+    echo "Opening PDF with: $OPEN"
   fi
 
   $OPEN $OUTPUT
